server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
api:
  key: api-key-here
config-changes-test: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  file: D:/microservice-application/logs/movie-info-service.log