server:
  port: 8085

spring:
  application:
    name: employee-app
  h2:
    console:
      enabled: true

keycloak:
  realm: javatechie
  auth-server-url: http://localhost:8080
  resource: springboot-keycloak
  public-client: true
  bearer-only: true