server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
         uri: file:///D:/microservice-application/spring-boot-microservices-workshop/config-files
   #      uri: https://github.com/Java-Techie-jt/cloud-config-server