server:
  port: 9191
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE-CATALOG-SERVICE
          uri: lb://MOVIE-CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
        - id: RATINGS-DATA-SERVICE
          uri: lb://RATINGS-DATA-SERVICE
          predicates:
            - Path=/ratingsdata/**
        - id: MOVIE-INFO-SERVICE
          uri: lb://MOVIE-INFO-SERVICE
          predicates:
            - Path=/api/movie/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: employee-app
          uri: lb://EMPLOYEE-APP
          predicates:
            - Path=/employees/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/javatechie